CREATE TABLE xark_status(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	date_print INTEGER NOT NULL,
	sync_status BOOLEAN DEFAULT FALSE,
	collect_status BOOLEAN DEFAULT FALSE,
	sync_date DATETIME,
	collect_date DATETIME,
	create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE data_xo(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	serial_num VARCHAR NOT NULL,
	uuid VARCHAR NOT NULL,
	create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE xark_except (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    except_type VARCHAR NOT NULL,
    except_messg VARCHAR NOT NULL,
	file_name VARCHAR NOT NULL,
    file_line VARCHAR NOT NULL,
    except_code VARCHAR NOT NULL,
	tb_except VARCHAR NOT NULL,
    server_name VARCHAR NOT NULL,
    user_name VARCHAR NOT NULL,
	create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
