CREATE TABLE xark_status(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	date_print INTEGER NOT NULL,
	sync_status BOOLEAN DEFAULT FALSE,
	collect_status BOOLEAN DEFAULT FALSE,
	sync_date DATETIME,
	collect_date DATETIME,
	create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE data_xo(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	serial_num VARCHAR NOT NULL,
	uuid VARCHAR NOT NULL,
	create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE xark_except (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    execttype VARCHAR NOT NULL,
    exectmessg VARCHAR NOT NULL,
    exectline VARCHAR NOT NULL,
    codesnipe VARCHAR NOT NULL,
    servername VARCHAR NOT NULL,
    execttime DATETIME DEFAULT CURRENT_TIMESTAMP
);
